# The dev -> staging -> prod pipeline is defined by the following
# three Stages and handles promotion of image tags.
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-rendered-branches
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: render-image

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-rendered-branches
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: render-image

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-rendered-branches
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      stages:
      - staging
  promotionTemplate:
    spec:
      steps:
      - task:
          name: render-image

---
# This render-envs Stage renders configuration to env specific branches
# and promote any changes made to the env/*/values.yaml, excluding
# changes to env/*/values-image.yaml, which are handled by the individual
# environment Stages.
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: render-envs
  namespace: kargo-rendered-branches
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task: {name: render-commit}
        vars: [{name: stage, value: dev}]
      - task: {name: render-commit}
        vars: [{name: stage, value: staging}]
      - task: {name: render-commit}
        vars: [{name: stage, value: prod}]
